---
- name: check ISO file
  stat:
    path: /rhel8.iso
  register: file_result

- name: copy ISO file - rhel8
  copy:
    src: ../files/rhel8.iso
    dest: /rhel8.iso
  when: not file_result.stat.exists

- name: mount iso file
  mount:
    src: /rhel8.iso
    path: /repo
    fstype: iso9660
    opts: loop
    state: mounted

- name: configure local BaseOS repo file
  yum_repository:
    name: "local-BaseOS"
    description: "RHEL8 Local Repo - BaseOS"
    baseurl: "file:///repo/BaseOS/"
    enabled: yes
    gpgcheck: no

- name: configure local AppStream repo file
  yum_repository:
    name: "local-AppStream"
    description: "RHEL8 Local Repo - AppStream"
    baseurl: "file:///repo/AppStream/"
    enabled: yes
    gpgcheck: no

