---
- name: create volume group
  lvg:
    vg: vg_database
    pvs: /dev/nvme0n2p1

- name: create logical volume
  lvol:
    lv: lv_mysql
    size: 512
    state: present
    vg: vg_database

- name: mount logical volume
  mount:
    fstype: xfs
    src: /dev/vg_database/lv_mysql
    path: /mnt/mysql_backups
    state: present

- name: install mysql package
  yum:
    disablerepo: local-AppStream
    enablerepo: mysql80-community
    name: "{{ packages }}"
  vars:
    packages:
    - mysql-community-server
    - python2-PyMySQL
    - python3-PyMySQL
    state: latest

- name: open port for incomming traffic
  firewalld:
    immediate: yes
    permanent: yes
    port: 3306/tcp
    state: enabled

- name: start/enable MySQL service
  service:
    name: mysqld
    enabled: yes
    state: started

- name: copy conf file to MySQL server
  copy:
    src: ../templates/my.cnf.j2
    dest: /etc/my.cnf
    mode: 0600
  notify: restart mysql

- name: set mysql root password
  mysql_user:
    login_user: root
    login_password: "{{ root | hash(sha512) }}"
    name: root
    password: "{{ database_password | hash(sha512) }}"
    state: present

