---
- name: package install
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - httpd
    - mod_ssl
    - php
    state: latest

- name: open incomming traffic port
  firewalld:
    port: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  with_items:
    - 80/tcp
    - 443/tcp

- name: template index.html
  copy:
    src: ../files/index.html.j2
    dest: /var/www/html/index.html 
  notify: restart httpd
