---
- name: Scheduled Tasks
  hosts: proxy
  become: yes

  tasks:
    - name: create cron job
      cron:
        name: Append Date
        hour: "*/1"
        job: date >> /var/log/time.log
        state: present


