---
- name: Software Repositories
  hosts: database
  become: yes

  tasks:
    - name: create repository in database groups
      yum_repository:
        name: "mysql80-community"
        description: MySQL 5.6 YUM Repo"
        baseurl: "http://repo.mysql.com/yum/mysql-5.6-community/el/7/x86_64/"
        gpgkey: "http://repo.mysql.com/RPM-GPG-KEY-mysql"
        gpgcheck: yes
        enabled: yes
        state: present


