---
- name: Download Roles From Ansible Galaxy and Use Them
  hosts: proxy
  become: yes

  roles:   
    - geerlingguy.haproxy

  post_tasks:
    - name: open service http
      firewalld:
        service: http
        immediate: yes
        permanent: yes
        state: enabled
