---
- name: Create and Use Templates to Create Cusomised Configuration Files
  hosts: database
  become: yes

  tasks:
    - name: template file
      template:
        src: server_list.j2
        dest: /etc/server_list.txt
        mode: 0600
        owner: automation
        setype: net_conf_t
