---
- name: GET Node Information
  hosts: all
  become: yes


  tasks:
    - name: get node's IPaddress
      debug:
        msg: "{{ ansible_default_ipv4.address }}"

    - name: test
      debug:
        msg: "Success"
      when: ansible_default_ipv4.address == "10.25.4.95"

